name: Clean runtime disk

on:
  pull_request:
    paths:
      - scripts/runtime_mgmt/clean-disk-flow/**
      - scripts/runtime_mgmt/create-clean-run.py
      - .github/workflows/clean-runtime-disk.yml

  schedule:
    - cron: "30 20 * * *"  # 4:30 Beijing Time (GMT+8)

  workflow_dispatch:

jobs:
  clean_runtime_disk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.9 environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Generate config.json for canary & production regions
        run: |
          echo '${{ secrets.TEST_WORKSPACE_CONFIG_JSON_CANARY }}' > ${{ github.workspace }}/scripts/runtime_mgmt/canary.json
          echo '${{ secrets.EXAMPLE_WORKSPACE_CONFIG_JSON_PROD }}' > ${{ github.workspace }}/scripts/runtime_mgmt/production.json

      - name: Submit run to clean
        shell: pwsh
        working-directory: ${{ github.workspace }}/scripts/runtime_mgmt
        run: |
          pip install promptflow[azure]
          python create-clean-run.py --path canary.json
          python create-clean-run.py --path production.json
